### ISSUE TITLE
Mistiming line output

### ISSUE THREAD

**Issue by shinchiro** [tp7/Sushi#17]
Sabagebu!-09:
http://www.solidfiles.com/d/b39659062d/Sabagebu!-09.rar
All lines in first chapter group appear late. For the next chapter groups, it give correct output

Shirobako-10:
http://www.solidfiles.com/d/eeb5b448b3/Shirobako-10.rar
I guess this is problem with search group. The typesetting lines in the end of chapter group "Part B" has moved to earlier part in chapter group "Preview" in the output

**Comment by tp7** [comment]
First part of the issue (sabagebu) is fixed in the commit linked above. The second part is yet another case of audio search working badly for almost silent segments and right now I don't have any real ideas on how to improve it.

By the way I noticed that you're always using `--window 100` - this is not safe in general and you're getting very large mistimings exactly because of it. You should consider using the `--max-window` setting if you want to counter possible errors where default window is not enough, it should be more safe for general use.

**Comment by shinchiro** [comment]
Thanks pointing for not using --window 100. I used Sushi.0.4.3c which  doesnt yet has --max-window option. Can I get latest version with all these bugfixes?

**Comment by tp7** [comment]
Get it [here](https://github.com/tp7/Sushi/releases/tag/0.4.4).

**Comment by shinchiro** [comment]
thanx

**Comment by shinchiro** [comment]
Dont know if this worth to mention or not, but I tried changed the <code>small_window</code> value to 0.5, the mistiming in the shirobako sample is completely gone. The typesetting lines appear perfectly.

Though, that small value doesnt fix in completely silent segment in one of my sample
